[build]
builder = "RAILPACK"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npm start"
numReplicas = 1
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
